# Persist log of Falco and Ginnungagap container
# For further forensic
volumes:
  falco-logs:
    driver: local
    name: shared-logs

# A bridge network to isolate Falco and Ginnungagap out
networks:
  ginnungagap-net:
    driver: bridge
    attachable: false

services:
  sandbox:
    container_name: ginnungagap-sandbox
    build:
      context: .
      dockerfile: sandbox.Dockerfile
    image: ghcr.io/alexanderslokov/ginnungagap-sandbox:ubuntu-noble-latest
    volumes:
      - /path/to/package.json:/app/package.json:ro
      - /path/to/package.lock:/app/package.lock:ro
    networks:
      - ginnungagap-net
    depends_on:
      - falco

  falco:
    image: falcosecurity/falco:0.43.0
    container_name: falco
    privileged: true
    command: falco -U # <-- BẬT UNBUFFERED OUTPUT ĐỂ LOG NHẢ NGAY LẬP TỨC
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      # Ginnungagap's rule to instruct Falco watchs the sandbox
      - ./falco/fourg_falco_rules.yaml:/etc/falco/falco_rules.local.yaml
      - ${FALCO_LOGS_VOLUME:-./falco-logs}:/var/log/falco
    networks:
      - ginnungagap-net
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"

  ginnungagap:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/alexanderslokov/ginnungagap:latest
    depends_on:
      - falco
    volumes:
      - ${FALCO_LOGS_VOLUME:-./falco-logs}:/var/log/falco # To parse logs and catch alerts from Falco ASAP
      - /var/run/docker.sock:/var/run/docker.sock         # Need to call Docker socket to pause/commit
    networks:
      - ginnungagap-net
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"
