# A bridge network to isolate Falco and Ginnungagap out
networks:
  ginnungagap-net:
    driver: bridge
    attachable: false

services:
  isolator:
    container_name: ginnungagap-isolator
    build:
      context: .
      dockerfile: isolator.Dockerfile
    image: ghcr.io/alexanderslokov/ginnungagap-isolator:ubuntu-noble-latest
    environment:
      - USER_NAME=${USER_NAME:-helvilette}
    cap_drop:
      - ALL
    cap_add:
      - SYS_PTRACE
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:mode=1777,size=256M
      - /home/${USER_NAME:-helvilette}:mode=1777,size=10240M,uid=1000,gid=1000
    volumes:
      - ./isolator/package.json:/opt/package.json.template:ro
    networks:
      - ginnungagap-net
    depends_on:
      - falco

  falco:
    image: falcosecurity/falco:0.43.0
    container_name: ginnungagap-pcr_thermocycler
    privileged: true
    # Turn on UNBUFFERED OUTPUT so we can catch log immediately from Falco
    # Override log format to JSON, so the control plane can unmarshall it
    command: falco -U -o json_output=true
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      # Instruct Falco to watch the isolator
      - ./pcr_thermocycler/falco_rules.local.yaml:/etc/pcr_thermocycler/falco_rules.local.yaml
    networks:
      - ginnungagap-net
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"

  lab:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/alexanderslokov/ginnungagap:latest
    depends_on:
      - falco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Need to call Docker socket to pause/commit
    networks:
      - ginnungagap-net
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"
