# A bridge network to isolate Falco and Ginnungagap out
networks:
  ginnungagap-net:
    driver: bridge
    attachable: false

services:
  sandbox:
    container_name: ginnungagap-sandbox
    build:
      context: .
      dockerfile: sandbox.Dockerfile
    image: ghcr.io/alexanderslokov/ginnungagap-sandbox:ubuntu-noble-latest
    environment:
      - USER_NAME=helvilette
    volumes:
      - ./sandbox/package.json:/home/helvilette/app/package.json:ro
      # - /path/to/package.lock:/home/helvilette/app/package.lock:ro
    networks:
      - ginnungagap-net
    depends_on:
      - falco
    cap_drop:
      - ALL
#    cap_add:
#      - SYS_PTRACE # Bắt buộc phải có để dùng strace cho forensics
    security_opt:
      - no-new-privileges:true
    # Sử dụng Seccomp/AppArmor mặc định của Docker
#    read_only: true # Chống malware ghi đè vào hệ thống file của container
#    tmpfs:
#      - /tmp:mode=1777,size=128M
#      - /home/helvilette:mode=1777,size=256M # Cho phép npm ghi vào home nhưng chỉ ở RAM
#      - /home/helvilette/app:mode=1777,size=256M # Cho phép npm ghi vào home nhưng chỉ ở RAM
  falco:
    image: falcosecurity/falco:0.43.0
    container_name: falco
    privileged: true
    # Turn on UNBUFFERED OUTPUT so we can catch log immediately from Falco
    # Override log format to JSON, so the control plane can unmarshall it
    command: falco -U -o json_output=true
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      # Ginnungagap's rule to instruct Falco watchs the sandbox
      - ./falco/falco_rules.local.yaml:/etc/falco/falco_rules.local.yaml
    networks:
      - ginnungagap-net
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"

  ginnungagap:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/alexanderslokov/ginnungagap:latest
    depends_on:
      - falco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Need to call Docker socket to pause/commit
    networks:
      - ginnungagap-net
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"
